
// Autogenerated
// -------------
// gulpfile.ts/wasm.ts --> generateBuildInfo

export const Build = {
    version: "0.72.5 (60b46321ee3e110b39b997e7734f3993)",
    buildSeed: 1646894204646,
    "wdosbox.shared.wasm": {
        "size": 3818724,
        "gzSize": 1087702
    },
    "wdosbox.shared.js": {
        "size": 213684,
        "gzSize": 48105
    },
    "wdosbox.wasm": {
        "size": 3709235,
        "gzSize": 1059161
    },
    "wdosbox.js": {
        "size": 269867,
        "gzSize": 65557
    },
    "wlibzip.wasm": {
        "size": 512765,
        "gzSize": 172801
    },
    "wlibzip.js": {
        "size": 174730,
        "gzSize": 44056
    }
,
};
